title: "Avenue of Abundance"
email: avenueofabundance@gmail.com
url: http://avenueofabundance.com
description: "To inspire an abundance mindset and broaden the mind to a richer and more fulfilling future"
#baseurl: "/hello-word"
timezone: UTC
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
author: IKEBUDU
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed


# Social
social:
  instagram: https://www.instagram.com/avenueofabundance/
  facebook: https://www.facebook.com/groups/320553697095694
  twitter: https://twitter.com/AvenueAbundance
  tik_tok: https://www.tiktok.com/@avenue.of.abundance?_t=8op01mrLDfL&_r=1

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

url: "https://avenueofabundance.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

include:
  - robots.txt
